### ISSUE TITLE
Task 2

### ISSUE THREAD

**Issue by karcagtamas** [Teaching-projects/SZE-MOSZE-2020-plusplusplus#2]
- [x] Add static `parseUnit` function with filename parameter (JSON format) [@Cerberuuus ]
- [x] Check file existance -> exception -> handle in the main [@Cerberuuus]
- [x] Overview 'parseUnit' function and its exception handling
- [x] Arguments parameter refactor. (Two file name) [@karcagtamas]
- [x] Reduced displayed text [@karcagtamas]
- [x] Add `units` folder with 3 unit [@karcagtamas]
- [x] 6 six different fight result (One CSV file) [@karcagtamas]
- [x] Revalidate fight results [@karcagtamas ]
- [x] Create `shell/python script` what is check two unit's fight and compare with the pregiven fight result. (Exception on mismatching) [@bencebaranyai]
- [x] Add GitHub Action pipeline (Run the 6 different fight result)

**Comment by karcagtamas** [comment]
What type of columns we need for the CSV file? @bencebaranyai

**Comment by bencebaranyai** [comment]
> What type of columns we need for the CSV file? @bencebaranyai

```csv
player1;player2;result
unit1.json;unit2.json;Unit1 wins. Remaining HP: 3500
```

Szerintem így jó @karcagtamas

**Comment by bencebaranyai** [comment]
@karcagtamas I think the last fight needs a revision. It fails the test

**Comment by karcagtamas** [comment]
> @karcagtamas I think the last fight needs a revision. It fails the test

Yap I know. I put a task to the list. I will check it today.

**Comment by karcagtamas** [comment]
@bencebaranyai I made the changes. All test ran down successfully :)

**Comment by karcagtamas** [comment]
@bencebaranyai @Cerberuuus 
I add a workflow file, please check it.
The name is `Test.yml`
Only build the project.
